name: Run Python Script

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Debug Node version   # 🔥 加這段確認
        run: node -v

      - name: Install packages
        run: |
          pip install requests pandas

      - name: Run script
        run: |
          python main.py
